name: NumericalSgps
version: 1.1.3
date: 18/09/2017
description: |
    A package for numerical semigroups

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/
    - name: Jose Morais

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/

contributors:
    - name: Benjamín Alarcón Heredia
      url: https://github.com/baheredia
    - name: Juan Ignacio García-García
      url: https://directorio.uca.es/cau/directorio.do?persona=11122
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Andrés Herrera-Poyatos
      url: https://github.com/andreshp
    - name: Max Horn
      url: http://www.quendi.de/en/math.html
    - name: Carlos Jesús Moreno Ávila
    - name: Ignacio Ojeda
      url: http://matematicas.unex.es/~ojedamc
    - name: Chris O'Neill
      url: https://www.math.ucdavis.edu/~coneill
    - name: Alessio Sammartano
      url: https://sites.google.com/site/alessiosammartano
    - name: Alfredo Sánchez-R. Navarro
      url: https://directorio.uca.es/cau/directorio.do?persona=12969
    - name: Klara Stokes
      url: http://www.his.se/en/about-us/Facts-and-figures/staff/Klara_Stokes
    - name: Strazzanti Francesco
      url: https://sites.google.com/site/francescostrazzanti
    - name: Giuseppe Zito

GAP: "4.7"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Singular"
      version: "12.04.28"
      url: "http://www.gap-system.org/HostedGapPackages/singular/"
    - name: "SingularInterface"
      version: "0.7.2"
    - name: "GradedModules"
      version: "2017.05.10"
      url: "http://homalg-project.github.io/homalg_project/GradedModules/"
    - name: "NormalizInterface"
      version: "0.9.8"
      url: "https://gap-packages.github.io/NormalizInterface"

www: https://gap-packages.github.io/numericalsgps
readme: README
packageinfo: https://gap-packages.github.io/numericalsgps/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/numericalsgps/releases/download/v1.1.3/NumericalSgps-1.1.3.tar.gz

abstract: |
    The <span class="pkgname">NumericalSgps</span> package, is a package to compute with numerical semigroups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
