<<<<<<< HEAD
name: NumericalSgps
version: 1.1.10
date: 2018-11-06
description: |
    A package for numerical semigroups
=======
name: GitHubPagesForGAP
version: 0.2
date: 2017-02-04
description: |
    A GitHub Pages generator for GAP packages
>>>>>>> 4d43033efdd1d95a15290331e5ee28ca345a1ad1

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/
    - name: Jose Morais

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/

contributors:
    - name: Benjamín Alarcón Heredia
      url: https://github.com/baheredia
    - name: Juan Ignacio García-García
      url: https://directorio.uca.es/cau/directorio.do?persona=11122
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Andrés Herrera-Poyatos
      url: https://github.com/andreshp
    - name: Max Horn
<<<<<<< HEAD
      url: http://www.quendi.de/en/math.html
    - name: Carlos Jesús Moreno Ávila
    - name: Ignacio Ojeda
      url: http://matematicas.unex.es/~ojedamc
    - name: Chris O'Neill
      url: https://www.math.ucdavis.edu/~coneill
    - name: Alessio Sammartano
      url: https://sites.google.com/site/alessiosammartano
    - name: Alfredo Sánchez-R. Navarro
      url: https://directorio.uca.es/cau/directorio.do?persona=12969
    - name: Klara Stokes
      url: http://www.his.se/en/about-us/Facts-and-figures/staff/Klara_Stokes
    - name: Strazzanti Francesco
      url: https://sites.google.com/site/francescostrazzanti
    - name: Giuseppe Zito

GAP: "4.7"

www: https://gap-packages.github.io/numericalsgps
readme: README.md
packageinfo: https://gap-packages.github.io/numericalsgps/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/numericalsgps/releases/download/v1.1.10/NumericalSgps-1.1.10.tar.gz

abstract: |
    The <span class="pkgname">NumericalSgps</span> package, is a package to compute with numerical semigroups.
=======
      url: http://www.quendi.de/math
    - name: Jan Itor

GAP: ">=4.8.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.1"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "orb"
      version: ">= 4.2"
      url: "https://gap-packages.github.io/orb"

www: https://gap-system.github.io/GitHubPagesForGAP/
readme: README.md
packageinfo: https://gap-system.github.io/GitHubPagesForGAP/PackageInfo.g
github: https://github.com/gap-system/GitHubPagesForGAP

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-system/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.bz2

abstract: |
    This is a pseudo package that contains no actual  <span class="pkgname">GAP</span> code. Instead, it is a template for other  GAP packages that allows to quickly setup GitHub Pages.
>>>>>>> 4d43033efdd1d95a15290331e5ee28ca345a1ad1

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    GitHub Pages, GAP.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HTI17</span>]   <b class='BibAuthor'>Horn, M., Thor, A. U. and Itor, J.</b>,
     <i class='BibTitle'>GitHubPagesForGAP, A GitHub Pages generator for GAP packages,
             Version 0.2</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-system.github.io/GitHubPagesForGAP/">https://gap-system.github.io/GitHubPagesForGAP/</a></span>.
    </p>
    

bibtex: |
    @misc{ GitHubPagesForGAP0.2,
      author =           {Horn, M. and Thor, A. U. and Itor, J.},
      title =            {{GitHubPagesForGAP}, A GitHub Pages generator for GAP packages, {V}ersion 0.2},
      month =            {Feb},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href                              {https://gap-system.github.io/GitHubPagesForGAP/}
                          {\texttt{https://gap-system.github.io/}\discretionary
                          {}{}{}\texttt{GitHubPagesForGAP/}}},
      keywords =         {GitHub Pages; GAP},
      printedkey =       {HTI17}
    }

