name: NumericalSgps
version: 1.0.1 dev
date: 01/09/2017
description: |
    A package for numerical semigroups

authors:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/
    - name: Jose Morais

maintainers:
    - name: Manuel Delgado
      url: http://www.fc.up.pt/cmup/mdelgado/
    - name: Pedro A. Garcia-Sanchez
      url: http://www.ugr.es/~pedro/

contributors:
    - name: Benjamín Alarcón Heredia
    - name: Andrés Herrera-Poyatos
      url: https://github.com/andreshp
    - name: Ignacio Ojeda
      url: http://matematicas.unex.es/~ojedamc
    - name: Chris O'Neill
      url: https://www.math.ucdavis.edu/~coneill
    - name: Alessio Sammartano
      url: https://sites.google.com/site/alessiosammartano
    - name: Alfredo Sánchez-R. Navarro
      url: https://directorio.uca.es/cau/directorio.do?persona=12969
    - name: Klara Stokes
      url: http://www.his.se/en/about-us/Facts-and-figures/staff/Klara_Stokes
    - name: Guiseppe Zito

GAP: "4.7"

suggested-pkgs:
    - name: "GAPDoc"
      version: "1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://gap-packages.github.io/numericalsgps/
readme: README
packageinfo: http://gap-packages.github.io/numericalsgps/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://gap-packages.github.io/numericalsgps/numericalsgps-1.0.1 dev.tar.gz

abstract: |
    The <span class="pkgname">NumericalSgps</span> package, is a package to compute with numerical semigroups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
